// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyCMwZeo44ZnlobW3PTwMZlDFuq2X9EjGe0',
      appId: '1:633724054405:web:797b32dd8c5f940a0c32ec',
      messagingSenderId: '633724054405',
      projectId: 'soretas-57c37',
      authDomain: 'soretas-57c37.firebaseapp.com',
      storageBucket: 'soretas-57c37.appspot.com',
      measurementId: 'G-E9CGLW36XR',
      databaseURL:
          'https://soretas-57c37-default-rtdb.europe-west1.firebasedatabase.app');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGHpL0PMNOhe30ROjIvSutoPT-z8z0bLY',
    appId: '1:633724054405:android:99b4567d33268c5d0c32ec',
    messagingSenderId: '633724054405',
    projectId: 'soretas-57c37',
    storageBucket: 'soretas-57c37.appspot.com',
    //databaseURL: 'https://soretas-57c37-default-rtdb.europe-west1.firebasedatabase.app'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_YdhZEP5dD6PZrq8Plbj8X2BlGPR0zBE',
    appId: '1:633724054405:ios:147ff7bfce7c917d0c32ec',
    messagingSenderId: '633724054405',
    projectId: 'soretas-57c37',
    storageBucket: 'soretas-57c37.appspot.com',
    iosBundleId: 'com.example.soretras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_YdhZEP5dD6PZrq8Plbj8X2BlGPR0zBE',
    appId: '1:633724054405:ios:147ff7bfce7c917d0c32ec',
    messagingSenderId: '633724054405',
    projectId: 'soretas-57c37',
    storageBucket: 'soretas-57c37.appspot.com',
    iosBundleId: 'com.example.soretras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMwZeo44ZnlobW3PTwMZlDFuq2X9EjGe0',
    appId: '1:633724054405:web:776ad2d787dbd3a60c32ec',
    messagingSenderId: '633724054405',
    projectId: 'soretas-57c37',
    authDomain: 'soretas-57c37.firebaseapp.com',
    storageBucket: 'soretas-57c37.appspot.com',
    measurementId: 'G-Y64ZJGF682',
  );
}
